cabcontext:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-context
    pullPolicy: Always
    tag: "1.3.3"

cabevent:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-event
    pullPolicy: Always
    tag: "1.3.3"

cabhistoric:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-historic
    pullPolicy: Always
    tag: "1.3.3"

cabrecommendation:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-recommendation
    pullPolicy: Always
    tag: "1.3.3"
  extraEnv:
    - name: RL_AGENT_API_URL
      value: "https://interactiveagent.passerelle.irt-systemx.fr/api/v1/recommendation"
    - name: RL_AGENT_API_TOKEN
      valueFrom:
        secretKeyRef:
          name: cab-recommendation
          key: rl-agent-api-token

cabcapitalization:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-capitalization
    pullPolicy: Always
    tag: "1.3.3"

frontend:
  image:
    repository: harbor.irtsysx.fr/docker-proxy-cache/irtsystemx/interactiveai-cab-standalone-frontend
    pullPolicy: Always
    tag: "1.3.3"