"""empty message

Revision ID: 1a445a4b65e2
Revises: 9a13cf7b8742
Create Date: 2023-11-30 14:30:33.260211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a445a4b65e2'
down_revision = '9a13cf7b8742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('of_uid', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_model', schema=None) as batch_op:
        batch_op.drop_column('of_uid')

    # ### end Alembic commands ###
