"""empty message

Revision ID: 85c494e79275
Revises: 1a445a4b65e2
Create Date: 2024-02-27 14:35:50.665020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85c494e79275'
down_revision = '1a445a4b65e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_model', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_event_id', sa.String(), nullable=True))
        batch_op.create_foreign_key(None, 'event_model', ['parent_event_id'], ['id_event'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_model', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_event_id')

    # ### end Alembic commands ###
