titre = "API PowerGrid - InteractiveAI"

[Connexion]
login_port = "auth/token"
cab_server_url_1 = "https://demo.interactiveai.irt-systemx.fr/"
cab_server_url_2 = "http://localhost:3200/"
cab_server_url_3 = "http://host.docker.internal:3200/"
cab_server_url_4 = "http://172.19.0.1:3200/"
cab_server_url_5 = "https://demo.interactiveai.irt-systemx.fr/"
cab_server_url_6 = "http://127.0.0.1/"
cab_server_url_7 = "http://192.168.208.118:3200/"

[Outputs]
activate = "yes"

[Outputs.Events]
event_port = "cab_event/api/v1/events"

[Outputs.Context]
context_port = "cabcontext/api/v1/contexts"
tempo = 30

[Inputs.Act]
url = "http://127.0.0.1:5000/api/v1/recommendations"
